### ISSUE TITLE
Error with a folder that is not available

### ISSUE THREAD

**Issue by Alaskarya** [LilZevi/AminoCoinGeneratorBo#1]
I have been trying to test the Coin Generator script in Termux for days, however I always get an error that says that there is no folder and therefore I cannot use the script. I checked with a friend, and he mentioned that the folder that said it was not available is where the emails are kept, and neither of them knows how to fix it. In more details, I mention again that I am testing the coin generator from Termux on an Android cell phone. Could it be that you could help me solve it? Or if you know of any solutions, I would greatly appreciate it.

![IMG_20210719_003937](https://user-images.githubusercontent.com/87629473/126099803-efc07774-5c42-4a68-afe8-fb9001bd7ad7.jpg)

@LilZevi

**Comment by Lavr-1q** [comment]
You not created a file emails.txt
Use `touch emails.txt`
And install text redactor example `pkg install micro`

**Comment by Alaskarya** [comment]
Thank you very much, it already works for me. ✨
