### ISSUE TITLE
Me again 

### ISSUE THREAD

**Issue by LucasAlgerDay** [LilZevi/AminoCoinGeneratorBo#4]
![Screenshot_20210729_180039](https://user-images.githubusercontent.com/88118098/127580203-4c548b0a-3584-4ba8-8efe-a6891783f374.jpg)
I cannot, why? :(

**Comment by LilZevi** [comment]
cd AminoCoinGeneratorBo

**Comment by LucasAlgerDay** [comment]
The same error.
