### ISSUE TITLE
не робит 

### ISSUE THREAD

**Issue by DruSenpai** [LilZevi/AminoCoinGeneratorBo#6]
Error! Your device is currently not supported, or the app is out of date. Please update to the latest version
![Снимок экрана (120)](https://user-images.githubusercontent.com/88430882/128158964-323b97bf-ebcb-4263-96d9-75ada8ed443e.png)

**Comment by LilZevi** [comment]
тупой долбаеб это не ошибка кода а фикс от амино

**Comment by DruSenpai** [comment]
> тупой долбаеб это не ошибка кода а фикс от амино

хуеглот, я всё сделал, оно теперь лишь в лотерею играет

**Comment by LilZevi** [comment]
> > тупой долбаеб это не ошибка кода а фикс от амино
> 
> хуеглот, я всё сделал, оно теперь лишь в лотерею играет

ало хуесос ебаный это тоже не ошибка кода а фикс от амино сын шалавы

**Comment by DruSenpai** [comment]
> > > тупой долбаеб это не ошибка кода а фикс от амино
> > 
> > 
> > хуеглот, я всё сделал, оно теперь лишь в лотерею играет
> 
> ало хуесос ебаный это тоже не ошибка кода а фикс от амино сын шалавы

Уебан, проблема кода, фикси девайс ид, ебланоид

**Comment by LilZevi** [comment]
Ало шалава ебаная нахуй чурка епта какая нахуй проблема кода если амино изменили систему девайсайди хуй тебе а не генератор монет сиди и посасывай членак немощь
