### ISSUE TITLE
Hey is this still working?

### ISSUE THREAD

**Issue by lhasxl** [LilZevi/AminoCoinGeneratorBo#7]
It says "Error! Your device is currently not supported, or the app is out of date. Please update to the latest version."
After i type:
-python AminoCoinGenerator.py
And it doesn't appear like it appears in your video

**Comment by LilZevi** [comment]
AminoCoinGeneratorBo Fixed.

**Comment by lhasxl** [comment]
How is it fixed

**Comment by LilZevi** [comment]
dumbass

**Comment by lhasxl** [comment]
Why im trying to make it work and its not working
