### ISSUE TITLE
It's not working, is there a solution?

### ISSUE THREAD

**Issue by Smiley5828** [LilZevi/AminoCoinGeneratorBo#8]
![Screenshot_2021-09-23-00-32-43](https://user-images.githubusercontent.com/91207246/134451159-1069c198-c322-414b-8876-5f4049cefd57.jpg)

**Comment by Lavr-1q** [comment]
u sure what you executed command `pip install -r requirements.txt`?

**Comment by Smiley5828** [comment]
Could you tell me which part to run please?

**Comment by Lavr-1q** [comment]
AminoCoinGenerator.py.
In first line occurred import amino error, maybe you not install amino.py (if this amino.py)

**Comment by LilZevi** [comment]
this script already fixed by Team Amino
