### ISSUE TITLE
issue why trying to coin transfer 

### ISSUE THREAD

**Issue by lhasxl** [LilZevi/AminoCoinGeneratorBo#9]
![photo_2021-10-06_04-32-21](https://user-images.githubusercontent.com/89989512/136126627-ad6af140-e614-4fe8-bfc6-84dec779a0cf.jpg)

**Comment by LilZevi** [comment]
script fixed by TA

**Comment by lhasxl** [comment]
Can i didn't understand can you explain more please

**Comment by uzair983** [comment]
+1 (743) 867-9396 msg in WhatsApp
